// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/sdk/trace (interfaces: SpanProcessor)
//
// Generated by this command:
//
//	mockgen -destination mock_spanprocessor_test.go -package telemetry go.opentelemetry.io/otel/sdk/trace SpanProcessor
//

// Package telemetry is a generated GoMock package.
package telemetry

import (
	context "context"
	reflect "reflect"

	trace "go.opentelemetry.io/otel/sdk/trace"
	gomock "go.uber.org/mock/gomock"
)

// MockSpanProcessor is a mock of SpanProcessor interface.
type MockSpanProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockSpanProcessorMockRecorder
	isgomock struct{}
}

// MockSpanProcessorMockRecorder is the mock recorder for MockSpanProcessor.
type MockSpanProcessorMockRecorder struct {
	mock *MockSpanProcessor
}

// NewMockSpanProcessor creates a new mock instance.
func NewMockSpanProcessor(ctrl *gomock.Controller) *MockSpanProcessor {
	mock := &MockSpanProcessor{ctrl: ctrl}
	mock.recorder = &MockSpanProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpanProcessor) EXPECT() *MockSpanProcessorMockRecorder {
	return m.recorder
}

// ForceFlush mocks base method.
func (m *MockSpanProcessor) ForceFlush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceFlush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceFlush indicates an expected call of ForceFlush.
func (mr *MockSpanProcessorMockRecorder) ForceFlush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceFlush", reflect.TypeOf((*MockSpanProcessor)(nil).ForceFlush), ctx)
}

// OnEnd mocks base method.
func (m *MockSpanProcessor) OnEnd(s trace.ReadOnlySpan) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEnd", s)
}

// OnEnd indicates an expected call of OnEnd.
func (mr *MockSpanProcessorMockRecorder) OnEnd(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEnd", reflect.TypeOf((*MockSpanProcessor)(nil).OnEnd), s)
}

// OnStart mocks base method.
func (m *MockSpanProcessor) OnStart(parent context.Context, s trace.ReadWriteSpan) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart", parent, s)
}

// OnStart indicates an expected call of OnStart.
func (mr *MockSpanProcessorMockRecorder) OnStart(parent, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockSpanProcessor)(nil).OnStart), parent, s)
}

// Shutdown mocks base method.
func (m *MockSpanProcessor) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockSpanProcessorMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockSpanProcessor)(nil).Shutdown), ctx)
}
