// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/sdk/log (interfaces: Processor)
//
// Generated by this command:
//
//	mockgen -destination mock_logprocessor_test.go -package telemetry go.opentelemetry.io/otel/sdk/log Processor
//

// Package telemetry is a generated GoMock package.
package telemetry

import (
	context "context"
	reflect "reflect"

	log "go.opentelemetry.io/otel/sdk/log"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
	isgomock struct{}
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockProcessor) Enabled(ctx context.Context, param log.EnabledParameters) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", ctx, param)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockProcessorMockRecorder) Enabled(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockProcessor)(nil).Enabled), ctx, param)
}

// ForceFlush mocks base method.
func (m *MockProcessor) ForceFlush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceFlush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceFlush indicates an expected call of ForceFlush.
func (mr *MockProcessorMockRecorder) ForceFlush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceFlush", reflect.TypeOf((*MockProcessor)(nil).ForceFlush), ctx)
}

// OnEmit mocks base method.
func (m *MockProcessor) OnEmit(ctx context.Context, record *log.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnEmit", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnEmit indicates an expected call of OnEmit.
func (mr *MockProcessorMockRecorder) OnEmit(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEmit", reflect.TypeOf((*MockProcessor)(nil).OnEmit), ctx, record)
}

// Shutdown mocks base method.
func (m *MockProcessor) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockProcessorMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockProcessor)(nil).Shutdown), ctx)
}
